import 'package:cosmic_companion/features/dso/domain/dso_object.dart';

abstract final class DsoCatalog {
  static const List<DsoObject> all = [
    // ── Galaxies ──────────────────────────────────────────────────────────────
    DsoObject(
      id: 'm31',
      namePl: 'Galaktyka Andromedy',
      nameEn: 'Andromeda Galaxy',
      catalogName: 'M31',
      type: DsoType.galaxy,
      raHours: 0.712,
      decDeg: 41.27,
      magnitude: 3.4,
      angularSizeArcmin: 190,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm33',
      namePl: 'Galaktyka Trójkąta',
      nameEn: 'Triangulum Galaxy',
      catalogName: 'M33',
      type: DsoType.galaxy,
      raHours: 1.565,
      decDeg: 30.65,
      magnitude: 5.7,
      angularSizeArcmin: 73,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm51',
      namePl: 'Galaktyka Wir',
      nameEn: 'Whirlpool Galaxy',
      catalogName: 'M51',
      type: DsoType.galaxy,
      raHours: 13.498,
      decDeg: 47.18,
      magnitude: 8.4,
      angularSizeArcmin: 11,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm101',
      namePl: 'Galaktyka Wiatraczek',
      nameEn: 'Pinwheel Galaxy',
      catalogName: 'M101',
      type: DsoType.galaxy,
      raHours: 14.053,
      decDeg: 54.35,
      magnitude: 7.9,
      angularSizeArcmin: 29,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm104',
      namePl: 'Galaktyka Sombrero',
      nameEn: 'Sombrero Galaxy',
      catalogName: 'M104',
      type: DsoType.galaxy,
      raHours: 12.665,
      decDeg: -11.62,
      magnitude: 8,
      angularSizeArcmin: 9,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'ngc891',
      namePl: 'NGC 891',
      nameEn: 'NGC 891 Edge-on Galaxy',
      catalogName: 'NGC 891',
      type: DsoType.galaxy,
      raHours: 2.377,
      decDeg: 42.35,
      magnitude: 10,
      angularSizeArcmin: 14,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm81',
      namePl: 'Galaktyka Bodego',
      nameEn: "Bode's Galaxy",
      catalogName: 'M81',
      type: DsoType.galaxy,
      raHours: 9.926,
      decDeg: 69.07,
      magnitude: 6.9,
      angularSizeArcmin: 26,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm82',
      namePl: 'Galaktyka Cygaro',
      nameEn: 'Cigar Galaxy',
      catalogName: 'M82',
      type: DsoType.galaxy,
      raHours: 9.931,
      decDeg: 69.68,
      magnitude: 8.4,
      angularSizeArcmin: 11,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'ngc253',
      namePl: 'Galaktyka Rzeźbiarza',
      nameEn: 'Sculptor Galaxy',
      catalogName: 'NGC 253',
      type: DsoType.galaxy,
      raHours: 0.793,
      decDeg: -25.29,
      magnitude: 7.2,
      angularSizeArcmin: 27,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm64',
      namePl: 'Galaktyka Czarne Oko',
      nameEn: 'Black Eye Galaxy',
      catalogName: 'M64',
      type: DsoType.galaxy,
      raHours: 12.945,
      decDeg: 21.68,
      magnitude: 8.5,
      angularSizeArcmin: 10,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm74',
      namePl: 'Galaktyka Fantom',
      nameEn: 'Phantom Galaxy',
      catalogName: 'M74',
      type: DsoType.galaxy,
      raHours: 1.612,
      decDeg: 15.78,
      magnitude: 9.4,
      angularSizeArcmin: 11,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm65',
      namePl: 'M65 (Trio Lwa)',
      nameEn: 'Leo Triplet — M65',
      catalogName: 'M65',
      type: DsoType.galaxy,
      raHours: 11.316,
      decDeg: 13.10,
      magnitude: 9.3,
      angularSizeArcmin: 8,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm66',
      namePl: 'M66 (Trio Lwa)',
      nameEn: 'Leo Triplet — M66',
      catalogName: 'M66',
      type: DsoType.galaxy,
      raHours: 11.337,
      decDeg: 12.99,
      magnitude: 8.9,
      angularSizeArcmin: 9,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'ngc4565',
      namePl: 'Galaktyka Igła',
      nameEn: 'Needle Galaxy',
      catalogName: 'NGC 4565',
      type: DsoType.galaxy,
      raHours: 12.606,
      decDeg: 25.99,
      magnitude: 9.6,
      angularSizeArcmin: 16,
      bestSeason: ObservingSeason.spring,
    ),

    // ── Emission Nebulae ──────────────────────────────────────────────────────
    DsoObject(
      id: 'm42',
      namePl: 'Mgławica Oriona',
      nameEn: 'Orion Nebula',
      catalogName: 'M42',
      type: DsoType.emissionNebula,
      raHours: 5.590,
      decDeg: -5.39,
      magnitude: 4,
      angularSizeArcmin: 90,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'm8',
      namePl: 'Mgławica Laguna',
      nameEn: 'Lagoon Nebula',
      catalogName: 'M8',
      type: DsoType.emissionNebula,
      raHours: 18.063,
      decDeg: -24.39,
      magnitude: 6,
      angularSizeArcmin: 90,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm20',
      namePl: 'Mgławica Trifid',
      nameEn: 'Trifid Nebula',
      catalogName: 'M20',
      type: DsoType.emissionNebula,
      raHours: 18.038,
      decDeg: -23.04,
      magnitude: 9,
      angularSizeArcmin: 28,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm16',
      namePl: 'Mgławica Orzeł',
      nameEn: 'Eagle Nebula',
      catalogName: 'M16',
      type: DsoType.emissionNebula,
      raHours: 18.313,
      decDeg: -13.79,
      magnitude: 6.4,
      angularSizeArcmin: 35,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc2244',
      namePl: 'Mgławica Różyczka',
      nameEn: 'Rosette Nebula',
      catalogName: 'NGC 2244',
      type: DsoType.emissionNebula,
      raHours: 6.532,
      decDeg: 4.86,
      magnitude: 4.8,
      angularSizeArcmin: 80,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'ic1805',
      namePl: 'Mgławica Serce',
      nameEn: 'Heart Nebula',
      catalogName: 'IC 1805',
      type: DsoType.emissionNebula,
      raHours: 2.545,
      decDeg: 61.45,
      magnitude: 6.5,
      angularSizeArcmin: 60,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm17',
      namePl: 'Mgławica Omega',
      nameEn: 'Omega Nebula',
      catalogName: 'M17',
      type: DsoType.emissionNebula,
      raHours: 18.346,
      decDeg: -16.18,
      magnitude: 6,
      angularSizeArcmin: 11,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc7000',
      namePl: 'Mgławica Ameryka Północna',
      nameEn: 'North America Nebula',
      catalogName: 'NGC 7000',
      type: DsoType.emissionNebula,
      raHours: 20.988,
      decDeg: 44.53,
      magnitude: 4,
      angularSizeArcmin: 120,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc281',
      namePl: 'Mgławica Pacman',
      nameEn: 'Pacman Nebula',
      catalogName: 'NGC 281',
      type: DsoType.emissionNebula,
      raHours: 0.883,
      decDeg: 56.63,
      magnitude: 7.4,
      angularSizeArcmin: 35,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'ngc2264',
      namePl: 'Mgławica Choinka',
      nameEn: 'Christmas Tree Cluster',
      catalogName: 'NGC 2264',
      type: DsoType.emissionNebula,
      raHours: 6.683,
      decDeg: 9.90,
      magnitude: 3.9,
      angularSizeArcmin: 20,
      bestSeason: ObservingSeason.winter,
    ),

    // ── Supernova Remnants ────────────────────────────────────────────────────
    DsoObject(
      id: 'm1',
      namePl: 'Mgławica Krab',
      nameEn: 'Crab Nebula',
      catalogName: 'M1',
      type: DsoType.supernovaRemnant,
      raHours: 5.575,
      decDeg: 22.01,
      magnitude: 8.4,
      angularSizeArcmin: 7,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'ngc6992',
      namePl: 'Mgławica Welon (Wschodnia)',
      nameEn: 'Eastern Veil Nebula',
      catalogName: 'NGC 6992',
      type: DsoType.supernovaRemnant,
      raHours: 20.940,
      decDeg: 31.72,
      magnitude: 7,
      angularSizeArcmin: 60,
      bestSeason: ObservingSeason.summer,
    ),

    // ── Planetary Nebulae ─────────────────────────────────────────────────────
    DsoObject(
      id: 'm57',
      namePl: 'Mgławica Pierścień',
      nameEn: 'Ring Nebula',
      catalogName: 'M57',
      type: DsoType.planetaryNebula,
      raHours: 18.893,
      decDeg: 33.02,
      magnitude: 8.8,
      angularSizeArcmin: 3,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm27',
      namePl: 'Mgławica Hantle',
      nameEn: 'Dumbbell Nebula',
      catalogName: 'M27',
      type: DsoType.planetaryNebula,
      raHours: 19.993,
      decDeg: 22.72,
      magnitude: 7.5,
      angularSizeArcmin: 8,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc7293',
      namePl: 'Mgławica Heliks',
      nameEn: 'Helix Nebula',
      catalogName: 'NGC 7293',
      type: DsoType.planetaryNebula,
      raHours: 22.493,
      decDeg: -20.84,
      magnitude: 7.3,
      angularSizeArcmin: 28,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'ngc6543',
      namePl: 'Mgławica Kocie Oko',
      nameEn: "Cat's Eye Nebula",
      catalogName: 'NGC 6543',
      type: DsoType.planetaryNebula,
      raHours: 17.976,
      decDeg: 66.63,
      magnitude: 8.1,
      angularSizeArcmin: 1,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc7662',
      namePl: 'Niebieska Kula Śniegu',
      nameEn: 'Blue Snowball Nebula',
      catalogName: 'NGC 7662',
      type: DsoType.planetaryNebula,
      raHours: 23.437,
      decDeg: 42.55,
      magnitude: 8.3,
      angularSizeArcmin: 1,
      bestSeason: ObservingSeason.autumn,
    ),

    // ── Reflection Nebulae ───────────────────────────────────────────────────
    DsoObject(
      id: 'm78',
      namePl: 'M78',
      nameEn: 'M78 Reflection Nebula',
      catalogName: 'M78',
      type: DsoType.reflectionNebula,
      raHours: 5.779,
      decDeg: 0.08,
      magnitude: 8,
      angularSizeArcmin: 8,
      bestSeason: ObservingSeason.winter,
    ),

    // ── Dark Nebulae ──────────────────────────────────────────────────────────
    DsoObject(
      id: 'b33',
      namePl: 'Mgławica Koński Łeb',
      nameEn: 'Horsehead Nebula',
      catalogName: 'B33',
      type: DsoType.darkNebula,
      raHours: 5.682,
      decDeg: -2.45,
      magnitude: 13,
      angularSizeArcmin: 8,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'ic1396',
      namePl: 'Mgławica Trąba Słonia',
      nameEn: 'Elephant Trunk Nebula',
      catalogName: 'IC 1396',
      type: DsoType.darkNebula,
      raHours: 21.648,
      decDeg: 57.49,
      magnitude: 3.5,
      angularSizeArcmin: 170,
      bestSeason: ObservingSeason.autumn,
    ),

    // ── Open Clusters ─────────────────────────────────────────────────────────
    DsoObject(
      id: 'm45',
      namePl: 'Plejady',
      nameEn: 'Pleiades',
      catalogName: 'M45',
      type: DsoType.openCluster,
      raHours: 3.783,
      decDeg: 24.12,
      magnitude: 1.6,
      angularSizeArcmin: 110,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'mel25',
      namePl: 'Hiady',
      nameEn: 'Hyades',
      catalogName: 'Mel 25',
      type: DsoType.openCluster,
      raHours: 4.450,
      decDeg: 15.87,
      magnitude: 0.5,
      angularSizeArcmin: 330,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'm44',
      namePl: 'Ul Pszczół',
      nameEn: 'Beehive Cluster',
      catalogName: 'M44',
      type: DsoType.openCluster,
      raHours: 8.673,
      decDeg: 19.98,
      magnitude: 3.7,
      angularSizeArcmin: 95,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'ngc869',
      namePl: 'Podwójna Gromada w Perseuszu',
      nameEn: 'Double Cluster',
      catalogName: 'NGC 869',
      type: DsoType.openCluster,
      raHours: 2.317,
      decDeg: 57.13,
      magnitude: 4.3,
      angularSizeArcmin: 30,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm35',
      namePl: 'M35',
      nameEn: 'M35 Open Cluster',
      catalogName: 'M35',
      type: DsoType.openCluster,
      raHours: 6.148,
      decDeg: 24.35,
      magnitude: 5.3,
      angularSizeArcmin: 28,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'm37',
      namePl: 'M37',
      nameEn: 'M37 Open Cluster',
      catalogName: 'M37',
      type: DsoType.openCluster,
      raHours: 5.872,
      decDeg: 32.55,
      magnitude: 6.2,
      angularSizeArcmin: 24,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'm34',
      namePl: 'M34',
      nameEn: 'M34 Open Cluster',
      catalogName: 'M34',
      type: DsoType.openCluster,
      raHours: 2.701,
      decDeg: 42.78,
      magnitude: 5.5,
      angularSizeArcmin: 35,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm11',
      namePl: 'Gromada Dzikie Kaczki',
      nameEn: 'Wild Duck Cluster',
      catalogName: 'M11',
      type: DsoType.openCluster,
      raHours: 18.852,
      decDeg: -6.27,
      magnitude: 6.3,
      angularSizeArcmin: 14,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm6',
      namePl: 'Gromada Motyl',
      nameEn: 'Butterfly Cluster',
      catalogName: 'M6',
      type: DsoType.openCluster,
      raHours: 17.673,
      decDeg: -32.25,
      magnitude: 4.2,
      angularSizeArcmin: 25,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm7',
      namePl: 'Gromada Ptolemeusza',
      nameEn: "Ptolemy's Cluster",
      catalogName: 'M7',
      type: DsoType.openCluster,
      raHours: 17.898,
      decDeg: -34.82,
      magnitude: 3.3,
      angularSizeArcmin: 80,
      bestSeason: ObservingSeason.summer,
    ),

    // ── Globular Clusters ─────────────────────────────────────────────────────
    DsoObject(
      id: 'm13',
      namePl: 'Gromada Herkulesa',
      nameEn: 'Hercules Cluster',
      catalogName: 'M13',
      type: DsoType.globularCluster,
      raHours: 16.695,
      decDeg: 36.46,
      magnitude: 5.8,
      angularSizeArcmin: 20,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm3',
      namePl: 'Gromada kulista M3',
      nameEn: 'Messier 3',
      catalogName: 'M3',
      type: DsoType.globularCluster,
      raHours: 13.703,
      decDeg: 28.37,
      magnitude: 6.2,
      angularSizeArcmin: 18,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm5',
      namePl: 'Gromada kulista M5',
      nameEn: 'Messier 5',
      catalogName: 'M5',
      type: DsoType.globularCluster,
      raHours: 15.310,
      decDeg: 2.08,
      magnitude: 5.6,
      angularSizeArcmin: 23,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm10',
      namePl: 'Gromada kulista M10',
      nameEn: 'Messier 10',
      catalogName: 'M10',
      type: DsoType.globularCluster,
      raHours: 16.952,
      decDeg: -4.10,
      magnitude: 6.6,
      angularSizeArcmin: 20,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm15',
      namePl: 'Gromada kulista M15',
      nameEn: 'Messier 15',
      catalogName: 'M15',
      type: DsoType.globularCluster,
      raHours: 21.499,
      decDeg: 12.17,
      magnitude: 6.4,
      angularSizeArcmin: 18,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm22',
      namePl: 'Gromada kulista M22',
      nameEn: 'Messier 22',
      catalogName: 'M22',
      type: DsoType.globularCluster,
      raHours: 18.607,
      decDeg: -23.90,
      magnitude: 5.1,
      angularSizeArcmin: 32,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm92',
      namePl: 'Gromada kulista M92',
      nameEn: 'Messier 92',
      catalogName: 'M92',
      type: DsoType.globularCluster,
      raHours: 17.286,
      decDeg: 43.13,
      magnitude: 6.5,
      angularSizeArcmin: 14,
      bestSeason: ObservingSeason.summer,
    ),
  ];
}
