import 'package:cosmic_companion/features/dso/domain/dso_object.dart';

abstract final class DsoCatalog {
  static const List<DsoObject> all = [
    // ── Galaxies ──────────────────────────────────────────────────────────────
    DsoObject(
      id: 'm31',
      namePl: 'Galaktyka Andromedy',
      nameEn: 'Andromeda Galaxy',
      catalogName: 'M31',
      type: DsoType.galaxy,
      raHours: 0.712,
      decDeg: 41.27,
      magnitude: 3.4,
      angularSizeArcmin: 190,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm33',
      namePl: 'Galaktyka Trójkąta',
      nameEn: 'Triangulum Galaxy',
      catalogName: 'M33',
      type: DsoType.galaxy,
      raHours: 1.565,
      decDeg: 30.65,
      magnitude: 5.7,
      angularSizeArcmin: 73,
      bestSeason: ObservingSeason.autumn,
    ),
    DsoObject(
      id: 'm51',
      namePl: 'Galaktyka Wir',
      nameEn: 'Whirlpool Galaxy',
      catalogName: 'M51',
      type: DsoType.galaxy,
      raHours: 13.498,
      decDeg: 47.18,
      magnitude: 8.4,
      angularSizeArcmin: 11,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm101',
      namePl: 'Galaktyka Wiatraczek',
      nameEn: 'Pinwheel Galaxy',
      catalogName: 'M101',
      type: DsoType.galaxy,
      raHours: 14.053,
      decDeg: 54.35,
      magnitude: 7.9,
      angularSizeArcmin: 29,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'm104',
      namePl: 'Galaktyka Sombrero',
      nameEn: 'Sombrero Galaxy',
      catalogName: 'M104',
      type: DsoType.galaxy,
      raHours: 12.665,
      decDeg: -11.62,
      magnitude: 8,
      angularSizeArcmin: 9,
      bestSeason: ObservingSeason.spring,
    ),
    DsoObject(
      id: 'ngc891',
      namePl: 'NGC 891',
      nameEn: 'NGC 891 Edge-on Galaxy',
      catalogName: 'NGC 891',
      type: DsoType.galaxy,
      raHours: 2.377,
      decDeg: 42.35,
      magnitude: 10,
      angularSizeArcmin: 14,
      bestSeason: ObservingSeason.autumn,
    ),

    // ── Emission Nebulae ──────────────────────────────────────────────────────
    DsoObject(
      id: 'm42',
      namePl: 'Mgławica Oriona',
      nameEn: 'Orion Nebula',
      catalogName: 'M42',
      type: DsoType.emissionNebula,
      raHours: 5.590,
      decDeg: -5.39,
      magnitude: 4,
      angularSizeArcmin: 90,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'm8',
      namePl: 'Mgławica Laguna',
      nameEn: 'Lagoon Nebula',
      catalogName: 'M8',
      type: DsoType.emissionNebula,
      raHours: 18.063,
      decDeg: -24.39,
      magnitude: 6,
      angularSizeArcmin: 90,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm20',
      namePl: 'Mgławica Trifid',
      nameEn: 'Trifid Nebula',
      catalogName: 'M20',
      type: DsoType.emissionNebula,
      raHours: 18.038,
      decDeg: -23.04,
      magnitude: 9,
      angularSizeArcmin: 28,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm16',
      namePl: 'Mgławica Orzeł',
      nameEn: 'Eagle Nebula',
      catalogName: 'M16',
      type: DsoType.emissionNebula,
      raHours: 18.313,
      decDeg: -13.79,
      magnitude: 6.4,
      angularSizeArcmin: 35,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc2244',
      namePl: 'Mgławica Różyczka',
      nameEn: 'Rosette Nebula',
      catalogName: 'NGC 2244',
      type: DsoType.emissionNebula,
      raHours: 6.532,
      decDeg: 4.86,
      magnitude: 4.8,
      angularSizeArcmin: 80,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'ic1805',
      namePl: 'Mgławica Serce',
      nameEn: 'Heart Nebula',
      catalogName: 'IC 1805',
      type: DsoType.emissionNebula,
      raHours: 2.545,
      decDeg: 61.45,
      magnitude: 6.5,
      angularSizeArcmin: 60,
      bestSeason: ObservingSeason.autumn,
    ),

    // ── Supernova Remnant ─────────────────────────────────────────────────────
    DsoObject(
      id: 'm1',
      namePl: 'Mgławica Krab',
      nameEn: 'Crab Nebula',
      catalogName: 'M1',
      type: DsoType.supernovaRemnant,
      raHours: 5.575,
      decDeg: 22.01,
      magnitude: 8.4,
      angularSizeArcmin: 7,
      bestSeason: ObservingSeason.winter,
    ),

    // ── Planetary Nebulae ─────────────────────────────────────────────────────
    DsoObject(
      id: 'm57',
      namePl: 'Mgławica Pierścień',
      nameEn: 'Ring Nebula',
      catalogName: 'M57',
      type: DsoType.planetaryNebula,
      raHours: 18.893,
      decDeg: 33.02,
      magnitude: 8.8,
      angularSizeArcmin: 3,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'm27',
      namePl: 'Mgławica Hantle',
      nameEn: 'Dumbbell Nebula',
      catalogName: 'M27',
      type: DsoType.planetaryNebula,
      raHours: 19.993,
      decDeg: 22.72,
      magnitude: 7.5,
      angularSizeArcmin: 8,
      bestSeason: ObservingSeason.summer,
    ),
    DsoObject(
      id: 'ngc7293',
      namePl: 'Mgławica Heliks',
      nameEn: 'Helix Nebula',
      catalogName: 'NGC 7293',
      type: DsoType.planetaryNebula,
      raHours: 22.493,
      decDeg: -20.84,
      magnitude: 7.3,
      angularSizeArcmin: 28,
      bestSeason: ObservingSeason.autumn,
    ),

    // ── Dark Nebulae ──────────────────────────────────────────────────────────
    DsoObject(
      id: 'b33',
      namePl: 'Mgławica Koński Łeb',
      nameEn: 'Horsehead Nebula',
      catalogName: 'B33',
      type: DsoType.darkNebula,
      raHours: 5.682,
      decDeg: -2.45,
      magnitude: 13,
      angularSizeArcmin: 8,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'ic1396',
      namePl: 'Mgławica Trąba Słonia',
      nameEn: 'Elephant Trunk Nebula',
      catalogName: 'IC 1396',
      type: DsoType.darkNebula,
      raHours: 21.648,
      decDeg: 57.49,
      magnitude: 3.5,
      angularSizeArcmin: 170,
      bestSeason: ObservingSeason.autumn,
    ),

    // ── Open Clusters ─────────────────────────────────────────────────────────
    DsoObject(
      id: 'm45',
      namePl: 'Plejady',
      nameEn: 'Pleiades',
      catalogName: 'M45',
      type: DsoType.openCluster,
      raHours: 3.783,
      decDeg: 24.12,
      magnitude: 1.6,
      angularSizeArcmin: 110,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'mel25',
      namePl: 'Hiady',
      nameEn: 'Hyades',
      catalogName: 'Mel 25',
      type: DsoType.openCluster,
      raHours: 4.450,
      decDeg: 15.87,
      magnitude: 0.5,
      angularSizeArcmin: 330,
      bestSeason: ObservingSeason.winter,
    ),
    DsoObject(
      id: 'm44',
      namePl: 'Ul Pszczół',
      nameEn: 'Beehive Cluster',
      catalogName: 'M44',
      type: DsoType.openCluster,
      raHours: 8.673,
      decDeg: 19.98,
      magnitude: 3.7,
      angularSizeArcmin: 95,
      bestSeason: ObservingSeason.spring,
    ),

    // ── Globular Clusters ─────────────────────────────────────────────────────
    DsoObject(
      id: 'm13',
      namePl: 'Gromada Herkulesa',
      nameEn: 'Hercules Cluster',
      catalogName: 'M13',
      type: DsoType.globularCluster,
      raHours: 16.695,
      decDeg: 36.46,
      magnitude: 5.8,
      angularSizeArcmin: 20,
      bestSeason: ObservingSeason.summer,
    ),
  ];
}
