arb-dir: lib/core/localization/arb
template-arb-file: app_pl.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/localization
nullable-getter: false
